[mgr]
ratio = [1, 3, 4]
show_hidden = false
show_symlink = true
sort_by = "natural"
sort_dir_first = true

[preview]
max_width = 1200
max_height = 1800
image_filter = "lanczos3"
image_quality = 85

[opener]
edit = [
  { run = 'zed "$@"', desc = "Zed", orphan = true, for = "macos" },
  { run = '${EDITOR:-vi} "$@"', block = true, desc = "Editor" },
]
reveal = [
  { run = 'open -R "$1"', desc = "Reveal in Finder", for = "macos" },
]
